### ISSUE TITLE
wrong language on login prompt

### ISSUE THREAD

**Issue by juergrinaldi** [caos/zitadel#2094] opened 2021-07-29 06:05 UTC
after entering the password (on english browser settings) I get german labels for the buttons on the MFA prompt

![image](https://user-images.githubusercontent.com/48990649/127439700-7c22438f-027c-4898-a4d4-677d1a513f47.png)

![image](https://user-images.githubusercontent.com/48990649/127439716-3631d515-755b-4fa5-a041-9aae20a63219.png)

**Comment by fgerschwiler** [comment] 2021-08-05 07:43
hi @juergrinaldi,
I just had a look at this and can't reproduce it:
![image](https://user-images.githubusercontent.com/38692350/128311282-aa550dce-25c9-4947-84d3-c4465711d22c.png)

Can you provide some more informations?
Do you see some errors in the developer console?

**Comment by livio-a** [comment] 2021-08-09 08:02
there were german texts in the english translation file... this has been fixed in version 1.23.0: https://github.com/caos/zitadel/pull/2016/files#diff-4453b2946f5b78481bc0bcdbb54912663c79a82e4a4672c4073dce6e0a47107fR85-R86

**Closed by livio-a** 2021-08-09 08:02 UTC
Labels: bug
