### ISSUE TITLE
remove 2nd password prompt after registration

### ISSUE THREAD

**Issue by juergrinaldi** [caos/zitadel#2104] opened 2021-07-29 13:12 UTC
(As discussed with @fforootd)
If I register a new org/user (where I set the password) the login process forces me to set a new password (like 1min after I already set one).
This is redundant, missleading an a hassle for the user.

If we have to give org admins (and the like) the possiblity to create new users for them, I suggest to use a different process where a temporary password will be generated automatically. (which is probably a safer approach anyway, as there still the problem how the initial set password gets to the user in the first place)

Or we don't set a password on the intial setup and the user sets it, after using the confirmation link.

**Comment by gc-ss** [comment] 2021-08-04 05:59
Agreed. My suggestion was to add support for magic links in general and use it as the first login link so it's a seamless experience

https://github.com/caos/zitadel/discussions/2075

This would ensure it actually was the real user (with the right email address) who logged in and not require them to change the password.

**Comment by fforootd** [comment] 2021-08-04 18:12
@gc-ss well we already use `tokens` within our links so it is kind of a magic link.

The problem with the 2nd password change is already due to be addressed. We have a internal appointment on the 12th August to design to refactor the process and expand the customization options for our customers.

**Comment by livio-a** [comment] 2021-11-08 12:03
I retested this on DEV with user registration and cannot reproduce it. I think we fixed this a while ago, so i will close this

**Closed by livio-a** 2021-11-08 12:03 UTC
Labels: go, backend
