### ISSUE TITLE
Renaming granted project

### ISSUE THREAD

**Issue by sueess** [caos/zitadel#2233] opened 2021-08-19 16:23 UTC
**Describe the bug**
Project renaming does not affect granted project in different organization.

**To Reproduce**
1. Create project
2. grant project to different organization
3. Rename project
4. Have a look at granted project --> name did not change

**Expected behavior**
The name of a project should always be the same everywhere

**Desktop (please complete the following information):**
 - Chrome, Mac

**Comment by adlerhurst** [comment] 2021-09-27 07:38
hi @sueess 

thanks for your report and sorry for the late reply.

We were not able to reproduce the bug. Could you provide further details?

Cheers

**Comment by fgerschwiler** [comment] 2022-02-03 08:32
I just tested this again and could not reproduce it. Due to this I will close this issue. If you still have this issue and you can provide us with some more informations we will reopen it.

**Closed by fgerschwiler** 2022-02-03 08:32 UTC
Labels: bug
